### ISSUE TITLE
[Bug] Extract-files does not detect output parameter is missing

### ISSUE THREAD

**Issue by SilasLaspada** [discimagechef/DiscImageChef#222]
### Prerequisites

* [X] Are you running the latest version?
* [X] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [X] I was running DiscImageChef under Windows 10...
* [X] ...in 64-bit

### Description

When I try to extract files from a floppy disk image, I get the error message "Error reading file: Value cannot be null. Parameter name: path". Happens with several different image files, including this one: https://drive.google.com/file/d/1TvO8rDuG1jA2lywdVoNc3ylQXbAKcdCK/view?usp=sharing

### Exact command line used:

`.\DiscImageChef.exe extract-files "Compaq Diagnostics.img" -d`

    
### Output of command execution with debug output enabled
```
PS C:\Users\silas\Documents\Alcohol 120%\000> .\DiscImageChef.exe extract-files "Compaq Diagnostics.img" -d
DiscImageChef 4.5.99.1693-00000000 built by DESKTOP-8B4K7NM in Debug
Copyright c 2011-2019 Natalia Portillo

DEBUG (Extract-Files command): --debug=True
DEBUG (Extract-Files command): --encoding=
DEBUG (Extract-Files command): --input=Compaq Diagnostics.img
DEBUG (Extract-Files command): --options=
DEBUG (Extract-Files command): --output=
DEBUG (Extract-Files command): --verbose=False
DEBUG (Extract-Files command): --xattrs=False
DEBUG (Extract-Files command): Parsed options:
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 1234189547
DEBUG (Anex86 plugin): fdihdr.hddtype = 538987842
DEBUG (Anex86 plugin): fdihdr.hdrSize = 8008501
DEBUG (Anex86 plugin): fdihdr.dskSize = 65794
DEBUG (Anex86 plugin): fdihdr.bps = 1073799170
DEBUG (Anex86 plugin): fdihdr.spt = 651275
DEBUG (Anex86 plugin): fdihdr.heads = 131090
DEBUG (Anex86 plugin): fdihdr.cylinders = 0
DEBUG (Format detection): Trying plugin Apple ][ Interleaved Disk Image
DEBUG (Format detection): Trying plugin Apple 2IMG
DEBUG (Format detection): Trying plugin Apple Disk Archival/Retrieval Tool
DEBUG (Format detection): Trying plugin Apple DiskCopy 4.2
DEBUG (Format detection): Trying plugin Apple New Disk Image Format
DEBUG (Format detection): Trying plugin Apple NIB
DEBUG (Format detection): Trying plugin Apple Universal Disk Image Format
DEBUG (Format detection): Trying plugin Basic Lisa Utility
DEBUG (Format detection): Trying plugin BlindWrite 4
DEBUG (Format detection): Trying plugin BlindWrite 5
DEBUG (Format detection): Trying plugin CDRDAO tocfile
DEBUG (Format detection): Trying plugin CDRWin cuesheet
DEBUG (Format detection): Trying plugin CisCopy Disk Image (DC-File)
DEBUG (Format detection): Trying plugin CloneCD
DEBUG (Format detection): Trying plugin CPCEMU Disk-File and Extended CPC Disk-File
DEBUG (CPCDSK plugin): header.magic = "?<?IBM  53z"
DEBUG (Format detection): Trying plugin d2f disk image
DEBUG (Format detection): Trying plugin D88 Disk Image
DEBUG (D88 plugin): d88hdr.name = "·?BM  53z"
DEBUG (D88 plugin): d88hdr.reserved is empty? = False
DEBUG (D88 plugin): d88hdr.write_protect = 0x02
DEBUG (D88 plugin): d88hdr.disk_type = D2 (0)
DEBUG (D88 plugin): d88hdr.disk_size = 0
DEBUG (Format detection): Trying plugin Digital Research DiskCopy
DEBUG (Format detection): Trying plugin DIM Disk Image
DEBUG (Format detection): Trying plugin DiscFerret
DEBUG (Format detection): Trying plugin DiscImageChef format
DEBUG (Format detection): Trying plugin DiscJuggler
DEBUG (DiscJuggler plugin): dscLen = -151587082
DEBUG (Format detection): Trying plugin Dreamcast GDI image
DEBUG (Format detection): Trying plugin Dunfield's IMD
DEBUG (Format detection): Trying plugin HD-Copy disk image
DEBUG (Format detection): Trying plugin IBM SaveDskF
DEBUG (Format detection): Trying plugin KryoFlux STREAM
DEBUG (Format detection): Trying plugin MAME Compressed Hunks of Data
DEBUG (Format detection): Trying plugin MAXI Disk image
DEBUG (MAXI Disk plugin): tmp_header.unknown = 235
DEBUG (MAXI Disk plugin): tmp_header.diskType = 60
DEBUG (MAXI Disk plugin): tmp_header.heads = 144
DEBUG (MAXI Disk plugin): tmp_header.cylinders = 73
DEBUG (MAXI Disk plugin): tmp_header.bytesPerSector = 66
DEBUG (MAXI Disk plugin): tmp_header.sectorsPerTrack = 77
DEBUG (MAXI Disk plugin): tmp_header.unknown2 = 32
DEBUG (MAXI Disk plugin): tmp_header.unknown3 = 32
DEBUG (Format detection): Trying plugin Microsoft VHDX
DEBUG (Format detection): Trying plugin Nero Burning ROM image
DEBUG (Nero plugin): imageStream.Length = 1474560
DEBUG (Nero plugin): footerV1.ChunkID = 0xF6F6F6F6
DEBUG (Nero plugin): footerV1.FirstChunkOffset = 4143380214
DEBUG (Nero plugin): footerV2.ChunkID = 0xF6F6F6F6
DEBUG (Nero plugin): footerV2.FirstChunkOffset = 17795682518166861558
DEBUG (Format detection): Trying plugin Parallels disk image
DEBUG (Format detection): Trying plugin PartClone disk image
DEBUG (Format detection): Trying plugin Partimage disk image
DEBUG (Format detection): Trying plugin QEMU Copy-On-Write disk image
DEBUG (Format detection): Trying plugin QEMU Copy-On-Write disk image v2
DEBUG (QCOW plugin): qHdr.magic = 0xEB3C9049
DEBUG (QCOW plugin): qHdr.version = 1112350752
DEBUG (Format detection): Trying plugin QEMU Enhanced Disk image
DEBUG (Format detection): Trying plugin Ray Arachelian's Disk IMage
DEBUG (Ray Arachelian's Disk IMage plugin): header.signature = ?<?IBM  53z
DEBUG (Ray Arachelian's Disk IMage plugin): header.diskType = 22
DEBUG (Ray Arachelian's Disk IMage plugin): header.heads = 62
DEBUG (Ray Arachelian's Disk IMage plugin): header.cylinders = 83
DEBUG (Ray Arachelian's Disk IMage plugin): header.sectorsPerTrack = 191
DEBUG (Ray Arachelian's Disk IMage plugin): header.signature matches? = False
DEBUG (Format detection): Trying plugin RS-IDE Hard Disk Image
DEBUG (Format detection): Trying plugin Spectrum Floppy Disk Image
DEBUG (Format detection): Trying plugin SuperCardPro
DEBUG (Format detection): Trying plugin Sydex CopyQM
DEBUG (Format detection): Trying plugin Sydex TeleDisk
DEBUG (Format detection): Trying plugin T98 Hard Disk Image
DEBUG (Format detection): Trying plugin T98-Next NHD r0 Disk Image
DEBUG (Format detection): Trying plugin Virtual98 Disk Image
DEBUG (Format detection): Trying plugin VirtualBox Disk Image
DEBUG (Format detection): Trying plugin VirtualPC
DEBUG (Format detection): Trying plugin VMware disk image
DEBUG (Format detection): Trying plugin Raw Disk Image
Image format identified by Raw Disk Image.
Error reading file: Value cannot be null.
Parameter name: path
DEBUG (Extract-Files command):    at System.IO.Directory.CreateDirectory(String path)
   at DiscImageChef.Commands.ExtractFilesCommand.Invoke(IEnumerable`1 arguments)
```

**Comment by darkstar** [comment]
Try adding  `-o <output-path>`

**Comment by claunia** [comment]
Change title to reflect real bug.
