### ISSUE TITLE
cannot extract files from a valid FAT12 disk image

### ISSUE THREAD

**Issue by skochinsky** [discimagechef/DiscImageChef#235]
### Prerequisites

* [x] Are you running the latest version?
* [x] Can you reproduce the problem in the debug version?

### Check and fill as appropiate:
* [x] I was running DiscImageChef 4.5.1.1692-1930cf95 under Windows 10.0.18362.356
* [x] ...using .NET Framework 
* [x] ...in 64-bit

### Description

cannot extract files from a valid FAT12 disk image

### Exact command line used:

`DiscImageChef extract-files -i win103.FDI -o 000 -d`

### Expected behavior:
Files extracted

### Actual behavior:
Error reading file: Object reference not set to an instance of an object.
DEBUG (Extract-Files command):    at DiscImageChef.Commands.ExtractFiles.DoExtractFiles(ExtractFilesOptions options)

   
### Output of command execution with debug output enabled
```
DEBUG (Extract-Files command): --debug=True
DEBUG (Extract-Files command): --verbose=False
DEBUG (Extract-Files command): --input=win103.FDI
DEBUG (Extract-Files command): --xattrs=False
DEBUG (Extract-Files command): --output=000
DEBUG (Extract-Files command): Parsed options:
DEBUG (Format detection): Trying plugin ACT Apricot Disk Image
DEBUG (Format detection): Trying plugin Alcohol 120% Media Descriptor Structure
DEBUG (Format detection): Trying plugin Anex86 Disk Image
DEBUG (Anex86 plugin): fdihdr.unknown = 0
DEBUG (Anex86 plugin): fdihdr.hddtype = 144
DEBUG (Anex86 plugin): fdihdr.hdrSize = 4096
DEBUG (Anex86 plugin): fdihdr.dskSize = 1261568
DEBUG (Anex86 plugin): fdihdr.bps = 1024
DEBUG (Anex86 plugin): fdihdr.spt = 8
DEBUG (Anex86 plugin): fdihdr.heads = 2
DEBUG (Anex86 plugin): fdihdr.cylinders = 77
DEBUG (Anex86 plugin): MediaType: NEC_525_HD
DEBUG (Extract-Files command): Correctly opened image file.
DEBUG (Extract-Files command): Image without headers is 1261568 bytes.
DEBUG (Extract-Files command): Image has 1232 sectors.
DEBUG (Extract-Files command): Image identifies disk type as NEC_525_HD.
DEBUG (Amiga RDB plugin): Possible magic at block 0 is 0xEB1C904E
DEBUG (Amiga RDB plugin): Possible magic at block 1 is 0xFEFFFF03
DEBUG (Amiga RDB plugin): Possible magic at block 2 is 0xC22AADE2
DEBUG (Amiga RDB plugin): Possible magic at block 3 is 0xFEFFFF03
DEBUG (Amiga RDB plugin): Possible magic at block 4 is 0xC22AADE2
DEBUG (Amiga RDB plugin): Possible magic at block 5 is 0x494F2020
DEBUG (Amiga RDB plugin): Possible magic at block 6 is 0x53595320
DEBUG (Amiga RDB plugin): Possible magic at block 7 is 0x00E5E5E5
DEBUG (Amiga RDB plugin): Possible magic at block 8 is 0x00E5E5E5
DEBUG (Amiga RDB plugin): Possible magic at block 9 is 0x00E5E5E5
DEBUG (Amiga RDB plugin): Possible magic at block 10 is 0x00E5E5E5
DEBUG (Amiga RDB plugin): Possible magic at block 11 is 0xE9DF9BE9
DEBUG (Amiga RDB plugin): Possible magic at block 12 is 0x00000000
DEBUG (Amiga RDB plugin): Possible magic at block 13 is 0x00000000
DEBUG (Amiga RDB plugin): Possible magic at block 14 is 0x00000000
DEBUG (Amiga RDB plugin): Possible magic at block 15 is 0x00000000
DEBUG (AppleMap Plugin): ddm.sbSig = 0xEB1C
DEBUG (AppleMap Plugin): ddm.sbBlockSize = 36942
DEBUG (AppleMap Plugin): ddm.sbBlocks = 1162027058
DEBUG (AppleMap Plugin): ddm.sbDevType = 11824
DEBUG (AppleMap Plugin): ddm.sbDevId = 12288
DEBUG (AppleMap Plugin): ddm.sbData = 0x04010100
DEBUG (AppleMap Plugin): ddm.sbDrvrCount = 704
DEBUG (Atari partition plugin): Boot code SHA1: 8ef17058f005dfaa4650eeaf6207d33374be5b4c
DEBUG (Atari partition plugin): table.icdEntries[0].flag = 0x50
DEBUG (Atari partition plugin): table.icdEntries[0].type = 0xC60608
DEBUG (Atari partition plugin): table.icdEntries[0].start = 34246836
DEBUG (Atari partition plugin): table.icdEntries[0].length = 3603766131
DEBUG (Atari partition plugin): table.icdEntries[1].flag = 0x0C
DEBUG (Atari partition plugin): table.icdEntries[1].type = 0xFE0E08
DEBUG (Atari partition plugin): table.icdEntries[1].start = 41158836
DEBUG (Atari partition plugin): table.icdEntries[1].length = 130882539
DEBUG (Atari partition plugin): table.icdEntries[2].flag = 0xEE
DEBUG (Atari partition plugin): table.icdEntries[2].type = 0x58C358
DEBUG (Atari partition plugin): table.icdEntries[2].start = 1488903937
DEBUG (Atari partition plugin): table.icdEntries[2].length = 3921608446
DEBUG (Atari partition plugin): table.icdEntries[3].flag = 0xC1
DEBUG (Atari partition plugin): table.icdEntries[3].type = 0x80F601
DEBUG (Atari partition plugin): table.icdEntries[3].start = 1397759630
DEBUG (Atari partition plugin): table.icdEntries[3].length = 503317030
DEBUG (Atari partition plugin): table.icdEntries[4].flag = 0x8A
DEBUG (Atari partition plugin): table.icdEntries[4].type = 0x460045
DEBUG (Atari partition plugin): table.icdEntries[4].start = 2282047349
DEBUG (Atari partition plugin): table.icdEntries[4].length = 204916486
DEBUG (Atari partition plugin): table.icdEntries[5].flag = 0x00
DEBUG (Atari partition plugin): table.icdEntries[5].type = 0x026010
DEBUG (Atari partition plugin): table.icdEntries[5].start = 915283456
DEBUG (Atari partition plugin): table.icdEntries[5].length = 38499815
DEBUG (Atari partition plugin): table.icdEntries[6].flag = 0x33
DEBUG (Atari partition plugin): table.icdEntries[6].type = 0xED1F58
DEBUG (Atari partition plugin): table.icdEntries[6].start = 1529607040
DEBUG (Atari partition plugin): table.icdEntries[6].length = 3691023134
DEBUG (Atari partition plugin): table.icdEntries[7].flag = 0x06
DEBUG (Atari partition plugin): table.icdEntries[7].type = 0x023BF3
DEBUG (Atari partition plugin): table.icdEntries[7].start = 1929775844
DEBUG (Atari partition plugin): table.icdEntries[7].length = 1963101150
DEBUG (Atari partition plugin): table.size = 1751457892
DEBUG (Atari partition plugin): table.entries[0].flag = 0x61
DEBUG (Atari partition plugin): table.entries[0].type = 0x746120
DEBUG (Atari partition plugin): table.entries[0].start = 1684632427
DEBUG (Atari partition plugin): table.entries[0].length = 5140256
DEBUG (Atari partition plugin): table.entries[1].flag = 0x73
DEBUG (Atari partition plugin): table.entries[1].type = 0x797374
DEBUG (Atari partition plugin): table.entries[1].start = 1701650534
DEBUG (Atari partition plugin): table.entries[1].length = 1768711539
DEBUG (Atari partition plugin): table.entries[2].flag = 0x00
DEBUG (Atari partition plugin): table.entries[2].type = 0x492F4F
DEBUG (Atari partition plugin): table.entries[2].start = 543519346
DEBUG (Atari partition plugin): table.entries[2].length = 1869742153
DEBUG (Atari partition plugin): table.entries[3].flag = 0x4F
DEBUG (Atari partition plugin): table.entries[3].type = 0x202020
DEBUG (Atari partition plugin): table.entries[3].start = 538976339
DEBUG (Atari partition plugin): table.entries[3].length = 1498633611
DEBUG (Atari partition plugin): table.badStart = 3968068654
DEBUG (Atari partition plugin): table.badLength = 1455900406
DEBUG (Atari partition plugin): table.checksum = 0x0000
DEBUG (BSD plugin): dl.magic on sector 0 at offset 0 = 0x4E901CEB (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 0 at offset 9 = 0x04003030 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 0 at offset 64 = 0x18CD12B4 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 0 at offset 128 = 0xF0240584 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 0 at offset 516 = 0xF446C700 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 1 at offset 0 = 0x03FFFFFE (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 1 at offset 9 = 0x09008007 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 1 at offset 64 = 0xE02D02C0 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 1 at offset 128 = 0x05805705 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 1 at offset 516 = 0x5B15A159 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 2 at offset 0 = 0xE2AD2AC2 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 2 at offset 9 = 0x42B32B22 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 2 at offset 64 = 0x2D82D72D (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 2 at offset 128 = 0x03302301 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 2 at offset 516 = 0x64054044 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 9 at offset 0 = 0xE5E5E500 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 9 at offset 9 = 0xE5E5E5E5 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 9 at offset 64 = 0xE5E5E500 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 9 at offset 128 = 0xE5E5E500 (expected 0x82564557)
DEBUG (BSD plugin): dl.magic on sector 9 at offset 516 = 0xE5E5E5E5 (expected 0x82564557)
DEBUG (GPT Plugin): hdr.signature = 0x6005004003FFFFFE
DEBUG (Human68k plugin): sectorSize = 1024
DEBUG (Human68k plugin): table.magic = C22AADE2
DEBUG (MBR plugin): xmlmedia = BlockMedia
DEBUG (MBR plugin): mbr.magic = 0000
DEBUG (SGIVH plugin): dvh.magic = 0xEB1C904E (should be 0x0BE5A941)
DEBUG (Sun plugin): dkl.dkl_magic = 0xF646
DEBUG (Sun plugin): dkl8.dkl_vtoc.v_sanity = 0x06C72EEB
DEBUG (Sun plugin): dkl16.dkl_vtoc.v_sanity = 0x00010104
DEBUG (VTOC plugin): sanity at 0 is 0x32204345 (should be 0xCA5E600D or 0x0D605ECA)
DEBUG (VTOC plugin): sanity at 1 is 0x60050040 (should be 0xCA5E600D or 0x0D605ECA)
DEBUG (VTOC plugin): sanity at 8 is 0xE5E5E5E5 (should be 0xCA5E600D or 0x0D605ECA)
DEBUG (VTOC plugin): sanity at 29 is 0xF9801E75 (should be 0xCA5E600D or 0x0D605ECA)
DEBUG (XENIX plugin): xnxtbl.p_magic = 0x0000 (should be 0x1234)
DEBUG (Extract-Files command): No partitions found
DEBUG (ADFS Plugin): oldMap0.checksum = 233
DEBUG (ADFS Plugin): oldChk0 = 77
DEBUG (ADFS Plugin): oldMap1.checksum = 171
DEBUG (ADFS Plugin): oldChk1 = 89
DEBUG (ADFS Plugin): newChk = 223
DEBUG (ADFS Plugin): map.zoneChecksum = 235
DEBUG (ADFS Plugin): bootChk = 184
DEBUG (ADFS Plugin): bBlock.checksum = 97
DEBUG (ProDOS plugin): prePointer = 10946
DEBUG (BTRFS Plugin): sbSectorOff = 64
DEBUG (BTRFS Plugin): sbSectorSize = 4
DEBUG (BTRFS Plugin): partition.PartitionStartSector = 0
DEBUG (BTRFS Plugin): btrfsSb.magic = 0x0000000000000000
DEBUG (CP/M Plugin): Trying to load definitions.
DEBUG (dump(8) plugin): old magic = 0x0000D000
DEBUG (dump(8) plugin): aix magic = 0x00020008
DEBUG (dump(8) plugin): new magic = 0x00020008
DEBUG (EFS plugin): magic at 1 = 0x40011560 (expected 0x00072959 or 0x0007295A)
DEBUG (Files-11 plugin): magic: "
DEBUG (Fossil plugin): magic at 0xECC3FEC5 (expected 0x3776AE89)
DEBUG (LIF plugin): magic 0x0000EB1C (expected 0x00008000)
DEBUG (Locus plugin): magic at 0 = 0x4E901CEB
DEBUG (Locus plugin): magic at 1 = 0x03FFFFFE
DEBUG (Locus plugin): magic at 2 = 0xE2AD2AC2
DEBUG (Locus plugin): magic at 3 = 0x03FFFFFE
DEBUG (Locus plugin): magic at 4 = 0xE2AD2AC2
DEBUG (Locus plugin): magic at 5 = 0x20204F49
DEBUG (Locus plugin): magic at 6 = 0x20535953
DEBUG (Locus plugin): magic at 7 = 0xE5E5E500
DEBUG (Locus plugin): magic at 8 = 0xE5E5E500
DEBUG (FAT plugin): Human bpc = 208
DEBUG (FAT plugin): Human clusters = 512
DEBUG (FAT plugin): Human big_clusters = 868257496
DEBUG (FAT plugin): Human expected clusters = 6065
DEBUG (FAT plugin): humanClustersCorrect = False
DEBUG (FAT plugin): humanOemCorrect = False
DEBUG (FAT plugin): humanBranchCorrect = False
DEBUG (FAT plugin): atari_oem_correct = True
DEBUG (FAT plugin): dos_oem_correct = True
DEBUG (FAT plugin): bps = 1024
DEBUG (FAT plugin): bits in bps = 1
DEBUG (FAT plugin): spc = 1
DEBUG (FAT plugin): correct_spc = True
DEBUG (FAT plugin): reserved_secs = 1
DEBUG (FAT plugin): fats_no = 2
DEBUG (FAT plugin): root_entries = 192
DEBUG (FAT plugin): sectors = 1232
DEBUG (FAT plugin): media_descriptor = 0xFE
DEBUG (FAT plugin): fat_sectors = 2
DEBUG (FAT plugin): msx_id = "t?
DEBUG (FAT plugin): huge_sectors = 13875273795666932744
DEBUG (FAT plugin): fat_id = 0xFE
DEBUG (FAT plugin): apricot_bps = 1281
DEBUG (FAT plugin): apricot_spc = 8
DEBUG (FAT plugin): apricot_correct_spc = True
DEBUG (FAT plugin): apricot_reserved_secs = 884
DEBUG (FAT plugin): apricot_fats_no = 184
DEBUG (FAT plugin): apricot_root_entries = 57344
DEBUG (FAT plugin): apricot_sectors = 49294
DEBUG (FAT plugin): apricot_media_descriptor = 0xBF
DEBUG (FAT plugin): apricot_fat_sectors = 320
DEBUG (RBF plugin): magic at 0 = 0x7404AA47 or 0xEB1C904E (expected 0x4372757A or 0x7A757243)
DEBUG (RBF plugin): magic at 4 = 0xC22EEDE2 or 0xC22AADE2 (expected 0x4372757A or 0x7A757243)
DEBUG (RBF plugin): magic at 15 = 0x00000000 or 0x00000000 (expected 0x4372757A or 0x7A757243)
DEBUG (UCSD Pascal Plugin): volEntry.firstBlock = -15830
DEBUG (UCSD Pascal Plugin): volEntry.lastBlock = -21022
DEBUG (UCSD Pascal Plugin): volEntry.entryType = 10927
DEBUG (UCSD Pascal Plugin): volEntry.volumeName = System.Byte[]
DEBUG (UCSD Pascal Plugin): volEntry.blocks = -19102
DEBUG (UCSD Pascal Plugin): volEntry.files = 11191
DEBUG (UCSD Pascal Plugin): volEntry.dummy = -32213
DEBUG (UCSD Pascal Plugin): volEntry.lastBoot = -18014
DEBUG (UCSD Pascal Plugin): volEntry.tail = 733725227
DEBUG (UNICOS plugin): magic = 0xEB1C904E45432032 (expected 0x6E6331667331636E)
DEBUG (UDF Plugin): anchor.tag.tagIdentifier = 53387
DEBUG (UDF Plugin): anchor.tag.descriptorVersion = 49361
DEBUG (UDF Plugin): anchor.tag.tagChecksum = 0x23
DEBUG (UDF Plugin): anchor.tag.reserved = 208
DEBUG (UDF Plugin): anchor.tag.tagSerialNumber = 49802
DEBUG (UDF Plugin): anchor.tag.descriptorCrc = 0xE0D1
DEBUG (UDF Plugin): anchor.tag.descriptorCrcLength = 57552
DEBUG (UDF Plugin): anchor.tag.tagLocation = 3771785425
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.length = 3771785425
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.location = 3330990289
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.length = 3771785425
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.location = 3771785425
DEBUG (UDF Plugin): anchor.tag.tagIdentifier = 36176
DEBUG (UDF Plugin): anchor.tag.descriptorVersion = 22150
DEBUG (UDF Plugin): anchor.tag.tagChecksum = 0xFF
DEBUG (UDF Plugin): anchor.tag.reserved = 22
DEBUG (UDF Plugin): anchor.tag.tagSerialNumber = 47184
DEBUG (UDF Plugin): anchor.tag.descriptorCrc = 0x0050
DEBUG (UDF Plugin): anchor.tag.descriptorCrcLength = 39504
DEBUG (UDF Plugin): anchor.tag.tagLocation = 1934
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.length = 91602955
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.location = 3942646200
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.length = 2311072514
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.location = 1996488262
DEBUG (UDF Plugin): anchor.tag.tagIdentifier = 7916
DEBUG (UDF Plugin): anchor.tag.descriptorVersion = 55438
DEBUG (UDF Plugin): anchor.tag.tagChecksum = 0x83
DEBUG (UDF Plugin): anchor.tag.reserved = 236
DEBUG (UDF Plugin): anchor.tag.tagSerialNumber = 65292
DEBUG (UDF Plugin): anchor.tag.descriptorCrc = 0x0A76
DEBUG (UDF Plugin): anchor.tag.descriptorCrcLength = 30463
DEBUG (UDF Plugin): anchor.tag.tagLocation = 108461832
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.length = 2566916536
DEBUG (UDF Plugin): anchor.mainVolumeDescriptorSequenceExtent.location = 4288303186
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.length = 2298478847
DEBUG (UDF Plugin): anchor.reserveVolumeDescriptorSequenceExtent.location = 1996485702
DEBUG (XFS plugin): magic at 0 = 0xEB1C904E (expected 0x58465342)
DEBUG (XFS plugin): magic at 1 = 0xFEFFFF03 (expected 0x58465342)
DEBUG (XFS plugin): magic at 2 = 0xC22AADE2 (expected 0x58465342)
Error reading file: Object reference not set to an instance of an object.
DEBUG (Extract-Files command):    at DiscImageChef.Commands.ExtractFiles.DoExtractFiles(ExtractFilesOptions options)
```
Image attached:
[win103.FDI.zip](https://github.com/discimagechef/DiscImageChef/files/3637384/win103.FDI.zip)

Side note: initially I redirected debug output to file and had to redo my paste several times because some of the "magic" outputs contained null bytes and the paste was getting cut off. I think some sanitization of raw string dumping might be useful.

### Extra notes
after converting image to raw and mouning with ImDisk I could copy the files from virtual drive so the FS is valid

**Comment by skochinsky** [comment]
latest build from ftp://discimagechef.app extracts successfully
